#!/bin/bash

if [[ -z "${CDT_BRANCH}" ]]; then
  CDT_BRANCH="master"
fi

if [[ -z "${CDT_GIT_URL}" ]]; then
  CDT_GIT_URL="https://github.com/devopswise/cdt.git"
fi

if [[ -z "${CDT_PLAYBOOK}" ]]; then
  CDT_PLAYBOOK="site.yml"
fi

if [[ -z "${CDT_SERVER_SSH_USER}" ]]; then
  CDT_SERVER_SSH_USER="centos"
fi

CDT_SOURCE_DIR=/opt/cdt/${CDT_BRANCH}
TIMESTAMP=$(date "+%Y%m%d%H%M%S")

if [[ -z "${AWS_DEFAULT_REGION}" ]]; then
  export AWS_DEFAULT_REGION=eu-west-1
fi

if [[ -z "${AWS_INSTANCE_TYPE}" ]]; then
  export AWS_INSTANCE_TYPE=t2.large
fi

set -e

if [[ ! -z "${DEBUG}" ]]; then
  set -o xtrace
fi

generate_pem_file() {
  # if KEY_PAIR is not defined we need to create one
  if [[ -z "${KEY_PAIR}" ]]; then
    KEY_PAIR="cdt-${TIMESTAMP}"
    PEM_FILE="${CDT_SOURCE_DIR}/${KEY_PAIR}.pem"
    echo generating new key-pair : ${KEY_PAIR}
    aws ec2 create-key-pair --key-name  "cdt-${TIMESTAMP}" \
      --query 'KeyMaterial' --output text > ${PEM_FILE}
    if [ $? -ne 0 ]; then
      echo 'Cannot create key pair'
      exit 1
    fi
    chmod 400 ${PEM_FILE}
  else
    if [[ ! -r "${PEM_FILE}" ]]; then
      echo "${PEM_FILE} is not readable by installer, please \
            use chown 1000:1000 mypemfile.pem"
      exit 1
    else
      echo using KEY_PAIR\(${KEY_PAIR}\) and PEM_FILE \(${PEM_FILE}\) provided.
    fi
  fi
}

provision_server() {
  #create a vpc
  vpcId=$(aws ec2 create-vpc --cidr-block 10.0.0.0/28 --query 'Vpc.VpcId' --output text)
  echo "vpcId="$vpcId > ${CDT_SOURCE_DIR}/.aws-config
  
  #enable dns
  aws ec2 modify-vpc-attribute --vpc-id $vpcId --enable-dns-support "{\"Value\":true}"
  aws ec2 modify-vpc-attribute --vpc-id $vpcId --enable-dns-hostnames "{\"Value\":true}"

  #Add Internet gateway
  internetGatewayId=$(aws ec2 create-internet-gateway --query 'InternetGateway.InternetGatewayId' --output text)
  aws ec2 attach-internet-gateway --internet-gateway-id $internetGatewayId --vpc-id $vpcId
  echo "internetGatewayId="$internetGatewayId >> ${CDT_SOURCE_DIR}/.aws-config
  
  #create a subnet
  subnetId=$(aws ec2 create-subnet --vpc-id $vpcId --cidr-block 10.0.0.0/28 --query 'Subnet.SubnetId' --output text)
  aws ec2 modify-subnet-attribute --subnet-id $subnetId --map-public-ip-on-launch
  echo "subnetId="$subnetId >> ${CDT_SOURCE_DIR}/.aws-config
  
  #configure route table
  routeTableId=$(aws ec2 create-route-table --vpc-id $vpcId --query 'RouteTable.RouteTableId' --output text)
  echo "routeTableId="$routeTableId >> ${CDT_SOURCE_DIR}/.aws-config
  aws ec2 associate-route-table --route-table-id $routeTableId --subnet-id $subnetId >> /dev/null
  aws ec2 create-route --route-table-id $routeTableId --destination-cidr-block 0.0.0.0/0 --gateway-id $internetGatewayId >> /dev/null

  #add a security group
  securityGroupId=$(aws ec2 create-security-group --group-name my-security-group --description "my-security-group" \
    --vpc-id $vpcId --query 'GroupId' --output text)
  aws ec2 authorize-security-group-ingress --group-id $securityGroupId --protocol tcp --port 22 --cidr 0.0.0.0/0
  aws ec2 authorize-security-group-ingress --group-id $securityGroupId --protocol tcp --port 443 --cidr 0.0.0.0/0
  aws ec2 authorize-security-group-ingress --group-id $securityGroupId --protocol tcp --port 80 --cidr 0.0.0.0/0
  aws ec2 authorize-security-group-ingress --group-id $securityGroupId --protocol tcp --port 8080 --cidr 0.0.0.0/0
  echo "securityGroupId="$securityGroupId >> ${CDT_SOURCE_DIR}/.aws-config
  
  #create ec2 instance
  echo creating new ec2 instance
  instance_id=$(aws ec2 run-instances --image-id ami-6e28b517 --count 1 \
    --instance-type ${AWS_INSTANCE_TYPE} --key-name ${KEY_PAIR} --security-group-ids $securityGroupId \
    --subnet-id $subnetId \
    --instance-initiated-shutdown-behavior stop \
    --output text --query 'Instances[*].InstanceId')
  echo "instanceId="$instance_id >> ${CDT_SOURCE_DIR}/.aws-config
  echo A new EC2 instance is created instance_id:$instance_id
  echo waiting $instance_id to become alive:
  while state=$(aws ec2 describe-instances --instance-ids $instance_id --output text \
      --query 'Reservations[*].Instances[*].State.Name'); test "$state" = "pending"; do
    sleep 1; echo -n '.'
  done; echo " $state"
  PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $instance_id | \
    grep PublicIpAddress | awk -F ":" '{print $2}' | sed 's/[",]//g' | tr -d ' ')
  echo public_ip=${PUBLIC_IP}
  
  if [[ ! -z "${ELASTIC_IP}" ]]; then
    echo "ELASTIC_IP is defined. associating it with instance"
    aws ec2 associate-address --instance-id $instance_id --public-ip ${ELASTIC_IP}
    echo $ELASTIC_IP is now associated with $instance_id
    PUBLIC_IP=${ELASTIC_IP}
  fi
}

setup_fqdn() {
  if [[ -z "${SERVER_FQDN}" ]]; then
    echo "using xip.io for fqdn"
    SERVER_FQDN=${PUBLIC_IP}.xip.io
  else
    echo "SERVER_FQDN is defined. using ${SERVER_FQDN} instead of XIP.IO"
  fi
}

display_server_vars() {
  echo SERVER_FQDN=${SERVER_FQDN} 
  echo PUBLIC_IP=${PUBLIC_IP}
  echo PEM_FILE=${PEM_FILE}
  echo KEY_PAIR=${KEY_PAIR}
  echo SERVER_FQDN=${SERVER_FQDN} >> ${CDT_SOURCE_DIR}/.aws-config
  echo PUBLIC_IP=${PUBLIC_IP} >> ${CDT_SOURCE_DIR}/.aws-config
  echo PEM_FILE=${PEM_FILE} >> ${CDT_SOURCE_DIR}/.aws-config
  echo KEY_PAIR=${KEY_PAIR} >> ${CDT_SOURCE_DIR}/.aws-config
  echo provisioning completed.
}

get_sources() {
  mkdir -p ${CDT_SOURCE_DIR}
  
  if [ ! -f ${CDT_SOURCE_DIR}/.cdt-version ]; then
      git clone -b ${CDT_BRANCH} ${CDT_GIT_URL} \
        ${CDT_SOURCE_DIR}
  else
      git -C ${CDT_SOURCE_DIR} checkout inventories/pro/hosts
      git -C ${CDT_SOURCE_DIR} checkout inventories/pro/group_vars/all/vars.yml
      git -C ${CDT_SOURCE_DIR} pull
  fi
}

set_config_vars() {
  sed -i "s@__dw_server_fqdn__@${SERVER_FQDN}@g" \
           ${CDT_SOURCE_DIR}/inventories/pro/hosts
  sed -i "s@__dw_private_key__@${PEM_FILE}@g" \
           ${CDT_SOURCE_DIR}/inventories/pro/hosts
  sed -i "s@__base_domain__@${SERVER_FQDN}@g" \
           ${CDT_SOURCE_DIR}/inventories/pro/group_vars/all/vars.yml
  sed -i "s@__base_domain__@${SERVER_FQDN}@g" \
           ${CDT_SOURCE_DIR}/cdt-config.json
}

run_ansible_code() {
  echo ansible-playbook -i ${CDT_SOURCE_DIR}/inventories/pro \
    ${CDT_SOURCE_DIR}/${CDT_PLAYBOOK} ${DEBUG}\
    --vault-password-file=${CDT_SOURCE_DIR}/ansible-vault-pass --extra-vars "@cdt-config.json"
  OLD_PWD=$PWD
  echo $OLD_PWD
  cd $CDT_SOURCE_DIR
  ansible-playbook -i ${CDT_SOURCE_DIR}/inventories/pro \
    ${CDT_SOURCE_DIR}/${CDT_PLAYBOOK} ${DEBUG} \
    --vault-password-file=${CDT_SOURCE_DIR}/ansible-vault-pass --extra-vars "@cdt-config.json"
  cd $OLD_PWD
}

display_development_info() {
  echo ' '
  echo cdt installed on ${SERVER_FQDN}, you can now access tools at www.${SERVER_FQDN}
  echo server will be terminated automatically in 2 hours, incase you forgot to terminate it
  echo if you want to develop or dig around, get into cdt-installer container first
  echo   docker exec -it cdt-installer bash
  echo ' '
  echo ' you can always share your thoughts on info@devopswise.co.uk '
  echo ' '
}

display_development_info2() {
  echo ' '
  echo cdt is installed on ${SERVER_FQDN}, you can access tools at www.${SERVER_FQDN}
  echo in this development container, you can either ssh to your instance by typing
  echo "  cdt --ssh"
  echo or again, inside this container you can modify ansible code in $CDT_SOURCE_DIR
  echo then apply changes by typing,
  echo "  ansible-playbook -i ${CDT_SOURCE_DIR}/inventories/pro ${CDT_SOURCE_DIR}/site.yml"
  echo ' '
}

terminate_server() {
  #ignore errors for next two commands
  set +e
  aws ec2 terminate-instances --instance-ids $instanceId ${DRY_RUN} > /dev/null
  while state=$(aws ec2 describe-instances --instance-ids $instanceId --output text \
      --query 'Reservations[*].Instances[*].State.Name'); test "$state" = "shutting-down"; do
    sleep 2; echo -n '.'
  done; echo " $state"
  set -e

  #aws release-address --public-ip $PUBLIC_IP
  aws ec2 detach-internet-gateway --internet-gateway-id $internetGatewayId --vpc-id $vpcId ${DRY_RUN}
  aws ec2 delete-internet-gateway --internet-gateway-id $internetGatewayId ${DRY_RUN}

  aws ec2 delete-security-group --group-id $securityGroupId ${DRY_RUN}
  aws ec2 delete-subnet --subnet-id $subnetId ${DRY_RUN}
  aws ec2 delete-route-table --route-table-id $routeTableId ${DRY_RUN}
  aws ec2 delete-vpc --vpc-id $vpcId ${DRY_RUN}
  rm ${CDT_SOURCE_DIR}/.aws-config
}

print_banner() {
  
echo "               _     _   ";
echo "              | |   | |  ";
echo "   ___      __| |   | |_ ";
echo "  / __|    / _\` |   | __|";
echo " | (__    | (_| |   | |_ ";
echo "  \___|    \__,_|    \__|";
echo "                         ";
                       
}

launch() {
  print_banner
  echo "Launching cdt..."
  get_sources
  if [[ -z "${DO_NOT_PROVISION_EC2}" ]]; then
    generate_pem_file
    provision_server
    sleep 15
  fi
  setup_fqdn
  set_config_vars
  run_ansible_code
  display_server_vars
  display_development_info
}

terminate() {
  if [ -f ${CDT_SOURCE_DIR}/.aws-config ]; then
    . ${CDT_SOURCE_DIR}/.aws-config
    echo "This will remove target server, you can always re-launch,"
    echo "a new server but you will lose data inside it if you didn't backup"
    while true; do
      read -p "Do you wish to terminate server? (y/n)" yn
      case $yn in
          [Yy]* ) terminate_server; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no.";;
      esac
    done
  else
    echo "no servers found. check .aws-config file"
  fi
}


ssh_connect() {
  if [ -f ${CDT_SOURCE_DIR}/.aws-config ]; then
    . ${CDT_SOURCE_DIR}/.aws-config
    if [ -f /root/.ssh/known_hosts ]; then
      ssh-keygen -f "/root/.ssh/known_hosts" -R ${SERVER_FQDN}
    fi
    ssh -i ${PEM_FILE} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${CDT_SERVER_SSH_USER}@${SERVER_FQDN}
  else
    "no servers found. check .aws-config file"
  fi
}

show_usage() {
  echo "Usage: $0 <operation>"
  echo "where operation is one of "
  echo " --launch     launches new instance"
  echo " --terminate  terminate instance"
  echo " --ssh        connect running to instance using ssh"
}

case "$1" in
   --launch|-l)
      launch
      ;;
   --terminate|-t)
      terminate
      ;;
   --ssh|-s)
      ssh_connect
      ;;
   --show-post-installation-info)
      print_banner
      display_development_info2
      ;;
   *)
      show_usage
      ;;
esac

exit 0



